# Generated by Django 4.2.7 on 2023-11-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobiliomodelis',
            name='variklis',
            field=models.CharField(default=1, max_length=20, verbose_name='Variklis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automobiliomodelis',
            name='year',
            field=models.IntegerField(default=1, max_length=4, verbose_name='Metai'),
            preserve_default=False,
        ),
    ]
