# Generated by Django 4.2.7 on 2023-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_remove_uzsakymoeilute_service_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UzsakymoEilute',
            new_name='UzsakymoSuvestine',
        ),
        migrations.AlterField(
            model_name='automobiliomodelis',
            name='year',
            field=models.IntegerField(verbose_name='Metai'),
        ),
    ]
