# Generated by Django 4.2.7 on 2023-11-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_rename_uzsakymoeilute_uzsakymosuvestine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomobilioModelis',
            new_name='AutomobiliuModeliai',
        ),
    ]
