# Generated by Django 4.2.7 on 2023-11-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_rename_paslauga_paslaugos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name_plural': 'Automobilis'},
        ),
        migrations.AlterModelOptions(
            name='automobiliumodeliai',
            options={'verbose_name_plural': 'Automobiliu modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslaugos',
            options={'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name_plural': 'Uzsakymas'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymosuvestine',
            options={'verbose_name_plural': 'Uzsakymo suvestine'},
        ),
        migrations.AddField(
            model_name='automobilis',
            name='coment',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Komentaras'),
        ),
    ]
