# Generated by Django 4.2.7 on 2023-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0007_alter_automobilis_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UzsakymoSuvestine',
            new_name='UzsakymoEilute',
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='automobiliumodeliai',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobiliu modeliai'},
        ),
        migrations.AlterModelOptions(
            name='paslaugos',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Uzsakymas', 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'Uzsakymo eilute', 'verbose_name_plural': 'Uzsakymu eilutes'},
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='coment',
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='cliet',
            field=models.CharField(help_text='Vardas/Pavarde', max_length=30, verbose_name='Klientas'),
        ),
        migrations.AlterField(
            model_name='automobiliumodeliai',
            name='brand',
            field=models.CharField(max_length=25, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='automobiliumodeliai',
            name='modelis',
            field=models.CharField(max_length=25, verbose_name='Modelis'),
        ),
        migrations.AlterField(
            model_name='automobiliumodeliai',
            name='variklis',
            field=models.CharField(max_length=10, verbose_name='Variklis'),
        ),
        migrations.AlterField(
            model_name='paslaugos',
            name='price',
            field=models.IntegerField(verbose_name='Kaina €'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
