# Generated by Django 4.2.7 on 2023-11-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_rename_uzsakymosuvestine_uzsakymoeilute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='vin_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='VIN kodas'),
        ),
        migrations.AlterField(
            model_name='uzsakymas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
