# Generated by Django 4.2.7 on 2023-11-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_uzsakymas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Laukiama detaliu'), ('r', 'Remontuojama'), ('a', 'Atlikta'), ('p', 'Priimtas uzsakymas')], help_text='Uzsakymo statusas', max_length=1),
        ),
    ]
