# Generated by Django 4.2.7 on 2023-11-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0012_alter_automobilis_id_alter_uzsakymoeilute_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Laukiama detaliu'), ('r', 'Remontuojama'), ('a', 'Atlikta'), ('p', 'Priimtas uzsakymas')], default='r', help_text='Uzsakymo statusas', max_length=1),
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='service_id',
        ),
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.paslaugos'),
        ),
    ]
