# Generated by Django 4.2.7 on 2023-11-11 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0014_remove_uzsakymoeilute_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='service_id',
        ),
        migrations.AddField(
            model_name='uzsakymoeilute',
            name='service_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.paslaugos'),
        ),
    ]
