# Generated by Django 4.2.7 on 2023-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0015_remove_uzsakymoeilute_service_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
