# Generated by Django 4.2.7 on 2023-11-15 10:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0018_uzsakymas_due_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilis',
            name='komentaras',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
