# Generated by Django 4.2.7 on 2023-11-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0019_automobilis_komentaras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilis',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Viršelis'),
        ),
    ]
